# Creates the time2live server on Hetzner Cloud from Windows PowerShell (no WSL, no hcloud CLI):
# SSH key, Cloud Firewall (22/80/443 tcp, 443 udp, icmp) and an Ubuntu 24.04 server whose
# cloud-init runs deploy/provision.sh on first boot. Safe to re-run: existing objects are reused
# and the firewall rules are re-applied.
#
#   $env:HCLOUD_TOKEN = "<API token, Read & Write>"
#   .\deploy\create-server.ps1                                # defaults below
#   .\deploy\create-server.ps1 -ServerType cx23 -Location hel1 -KeyPath $HOME\.ssh\time2live.pub
#   .\deploy\create-server.ps1 -DryRun                        # only write cloud-init.yaml, call nothing
param(
  [string]$Name = 'time2live',
  [string]$Location = 'hel1',
  [string]$ServerType = 'cx23',
  [string]$Image = 'ubuntu-24.04',
  [string]$KeyPath = (Join-Path $HOME '.ssh\time2live.pub'),
  [string]$ApiBase = 'https://api.hetzner.cloud/v1',
  [switch]$DryRun
)
$ErrorActionPreference = 'Stop'

if (-not (Test-Path $KeyPath)) { throw "SSH public key not found: $KeyPath (create it: ssh-keygen -t ed25519 -f $HOME\.ssh\time2live)" }
$publicKey = (Get-Content -Raw $KeyPath).Trim()
if ($publicKey -notmatch '^(ssh-|ecdsa-|sk-)') { throw "$KeyPath does not look like an SSH public key" }

# ---- cloud-init: embeds provision.sh + backup units (same output as make-cloud-init.sh) ----
function Get-B64([string]$path) {
  # Raw bytes: the .sh files are LF in the repo (.gitattributes) and must stay that way.
  [Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $PSScriptRoot $path)))
}
$keyForShell = $publicKey.Replace("'", '')
$userData = @"
#cloud-config
# Generated by deploy/create-server.ps1 - edit provision.sh instead.
package_update: false
write_files:
  - path: /root/time2live/provision.sh
    permissions: '0700'
    encoding: b64
    content: $(Get-B64 'provision.sh')
  - path: /root/time2live/systemd/time2live-backup.service
    permissions: '0644'
    encoding: b64
    content: $(Get-B64 'systemd/time2live-backup.service')
  - path: /root/time2live/systemd/time2live-backup.timer
    permissions: '0644'
    encoding: b64
    content: $(Get-B64 'systemd/time2live-backup.timer')
runcmd:
  - [bash, -c, 'DEPLOY_SSH_KEY="$keyForShell" bash /root/time2live/provision.sh > /var/log/time2live-provision.log 2>&1']
"@ -replace "`r`n", "`n"

$any = @('0.0.0.0/0', '::/0')
$rules = @(
  @{ direction = 'in'; protocol = 'tcp'; port = '22'; source_ips = $any; description = 'ssh' },
  @{ direction = 'in'; protocol = 'tcp'; port = '80'; source_ips = $any; description = 'http' },
  @{ direction = 'in'; protocol = 'tcp'; port = '443'; source_ips = $any; description = 'https' },
  @{ direction = 'in'; protocol = 'udp'; port = '443'; source_ips = $any; description = 'http3' },
  @{ direction = 'in'; protocol = 'icmp'; source_ips = $any; description = 'ping' }
)

if ($DryRun) {
  $out = Join-Path (Get-Location) 'cloud-init.yaml'
  [IO.File]::WriteAllText($out, $userData, (New-Object Text.UTF8Encoding $false))
  Write-Host "dry run: wrote $out (paste it as 'Cloud config' in the Hetzner Console)."
  Write-Host "firewall rules: tcp 22, 80, 443; udp 443; icmp (inbound, any source)"
  exit 0
}

if (-not $env:HCLOUD_TOKEN) {
  throw 'Set $env:HCLOUD_TOKEN first (Hetzner Console -> your project -> Security -> API tokens, Read & Write).'
}
$headers = @{ Authorization = "Bearer $($env:HCLOUD_TOKEN)" }

function Invoke-Hcloud([string]$Method, [string]$Path, $Body = $null) {
  $params = @{ Method = $Method; Uri = "$ApiBase$Path"; Headers = $headers; ContentType = 'application/json' }
  if ($null -ne $Body) { $params.Body = ($Body | ConvertTo-Json -Depth 10 -Compress) }
  try {
    return Invoke-RestMethod @params
  } catch {
    $detail = $_.ErrorDetails.Message
    throw "Hetzner API $Method $Path failed: $($_.Exception.Message) $detail"
  }
}

# 1. SSH key (matched by content, so an already uploaded key under another name is reused)
$fingerprintKey = ($publicKey -split '\s+')[0..1] -join ' '
$ssh = (Invoke-Hcloud GET '/ssh_keys?per_page=50').ssh_keys |
  Where-Object { (($_.public_key -split '\s+')[0..1] -join ' ') -eq $fingerprintKey } | Select-Object -First 1
if ($ssh) {
  Write-Host "ssh key      reusing '$($ssh.name)'"
} else {
  $ssh = (Invoke-Hcloud POST '/ssh_keys' @{ name = $Name; public_key = $publicKey }).ssh_key
  Write-Host "ssh key      uploaded as '$Name'"
}

# 2. Cloud Firewall (rules re-applied every run)
$firewall = (Invoke-Hcloud GET "/firewalls?name=$Name").firewalls | Select-Object -First 1
if ($firewall) {
  Invoke-Hcloud POST "/firewalls/$($firewall.id)/actions/set_rules" @{ rules = $rules } | Out-Null
  Write-Host "firewall     '$Name' rules updated (tcp 22/80/443, udp 443, icmp)"
} else {
  $firewall = (Invoke-Hcloud POST '/firewalls' @{ name = $Name; rules = $rules }).firewall
  Write-Host "firewall     '$Name' created (tcp 22/80/443, udp 443, icmp)"
}

# 3. Server
$server = (Invoke-Hcloud GET "/servers?name=$Name").servers | Select-Object -First 1
if ($server) {
  Write-Host "server       '$Name' already exists (not recreated; cloud-init only runs on first boot)"
  $attached = @($server.public_net.firewalls | ForEach-Object { $_.id }) -contains $firewall.id
  if (-not $attached) {
    Invoke-Hcloud POST "/firewalls/$($firewall.id)/actions/apply_to_resources" @{
      apply_to = @(@{ type = 'server'; server = @{ id = $server.id } })
    } | Out-Null
    Write-Host "firewall     attached to '$Name'"
  }
} else {
  $server = (Invoke-Hcloud POST '/servers' @{
      name               = $Name
      server_type        = $ServerType
      location           = $Location
      image              = $Image
      ssh_keys           = @($ssh.id)
      firewalls          = @(@{ firewall = $firewall.id })
      public_net         = @{ enable_ipv4 = $true; enable_ipv6 = $true }
      start_after_create = $true
      user_data          = $userData
    }).server
  Write-Host "server       creating '$Name' ($ServerType, $Location, $Image)"
}

$deadline = (Get-Date).AddMinutes(5)
while ($true) {
  $server = (Invoke-Hcloud GET "/servers/$($server.id)").server
  if ($server.status -eq 'running' -and $server.public_net.ipv4.ip) { break }
  if ((Get-Date) -gt $deadline) { throw "server not running after 5 minutes (status: $($server.status))" }
  Start-Sleep -Seconds 5
}

$ipv4 = $server.public_net.ipv4.ip
# Hetzner assigns a /64; the server itself answers on <prefix>::1.
$ipv6 = if ($server.public_net.ipv6.ip) { ($server.public_net.ipv6.ip -replace '::/64$', '') + '::1' } else { '' }
$keyFile = $KeyPath -replace '\.pub$', ''

Write-Host ''
Write-Host "server       $Name is running"
Write-Host "IPv4         $ipv4"
Write-Host "IPv6         $ipv6"
Write-Host ''
Write-Host 'Next steps (docs/OPERATIONS.md):'
Write-Host "  1. DNS:  A  time2live.xyz -> $ipv4    AAAA  time2live.xyz -> $ipv6   (same for www)"
Write-Host "  2. Add to $(Join-Path $HOME .ssh config):"
Write-Host "       Host time2live"
Write-Host "         HostName $ipv4"
Write-Host "         User deploy"
Write-Host "         IdentityFile $keyFile"
Write-Host "  3. In ~3-5 minutes:  ssh time2live 'sudo tail -n 20 /var/log/time2live-provision.log'"
