#!/usr/bin/env bash
# Prints cloud-init user-data that runs provision.sh (plus the backup units) on first boot.
#   deploy/make-cloud-init.sh ~/.ssh/id_ed25519.pub > cloud-init.yaml
# provision.sh stays the single source of truth; this only embeds it.
set -Eeuo pipefail
KEY_FILE="${1:?usage: make-cloud-init.sh <ssh-public-key-file>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
key="$(head -n1 "$KEY_FILE")"
[[ "$key" =~ ^(ssh-|ecdsa-|sk-) ]] || { echo "$KEY_FILE does not look like an SSH public key" >&2; exit 1; }

b64() { base64 -w0 <"$1" 2>/dev/null || base64 <"$1" | tr -d '\n'; }

cat <<YAML
#cloud-config
# Generated by deploy/make-cloud-init.sh — do not edit; edit provision.sh instead.
package_update: false
write_files:
  - path: /root/time2live/provision.sh
    permissions: '0700'
    encoding: b64
    content: $(b64 "$HERE/provision.sh")
  - path: /root/time2live/systemd/time2live-backup.service
    permissions: '0644'
    encoding: b64
    content: $(b64 "$HERE/systemd/time2live-backup.service")
  - path: /root/time2live/systemd/time2live-backup.timer
    permissions: '0644'
    encoding: b64
    content: $(b64 "$HERE/systemd/time2live-backup.timer")
runcmd:
  - [bash, -c, 'DEPLOY_SSH_KEY="$key" bash /root/time2live/provision.sh > /var/log/time2live-provision.log 2>&1']
YAML
